// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8ltfywT--r5swx3HJqtxdfuXBCgu5Dk',
    appId: '1:620181980784:web:a4353c0b99529ba03516b5',
    messagingSenderId: '620181980784',
    projectId: 'chat-app-3caec',
    authDomain: 'chat-app-3caec.firebaseapp.com',
    storageBucket: 'chat-app-3caec.firebasestorage.app',
    measurementId: 'G-R8RPWT7SQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2i7y9IPhFbQ9FVnahxJUMgMtD8XAYqI',
    appId: '1:620181980784:android:c0efcb8874b264063516b5',
    messagingSenderId: '620181980784',
    projectId: 'chat-app-3caec',
    storageBucket: 'chat-app-3caec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDww4qDAI10wru3QKnXx_eOnXbc0Ga0MQY',
    appId: '1:620181980784:ios:9e5c74d2e6bcfe303516b5',
    messagingSenderId: '620181980784',
    projectId: 'chat-app-3caec',
    storageBucket: 'chat-app-3caec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDww4qDAI10wru3QKnXx_eOnXbc0Ga0MQY',
    appId: '1:620181980784:ios:9e5c74d2e6bcfe303516b5',
    messagingSenderId: '620181980784',
    projectId: 'chat-app-3caec',
    storageBucket: 'chat-app-3caec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8ltfywT--r5swx3HJqtxdfuXBCgu5Dk',
    appId: '1:620181980784:web:b65c4aa6f893d6fc3516b5',
    messagingSenderId: '620181980784',
    projectId: 'chat-app-3caec',
    authDomain: 'chat-app-3caec.firebaseapp.com',
    storageBucket: 'chat-app-3caec.firebasestorage.app',
    measurementId: 'G-MH7B403DTP',
  );
}
